spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive_demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
